version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stepzy-postgres
    environment:
      POSTGRES_USER: stepzy_user
      POSTGRES_PASSWORD: stepzy_dev_2024
      POSTGRES_DB: stepzy_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stepzy-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: